# Generated by Django 2.2.7 on 2019-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
