# Generated by Django 2.2.7 on 2019-11-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0003_schemes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schemes',
            new_name='Scheme',
        ),
    ]
