# Generated by Django 2.2.7 on 2019-11-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0007_schemestructure_is_conclusion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchemeStructure',
        ),
    ]
