# Generated by Django 2.2.7 on 2019-11-24 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0008_delete_schemestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('ordering', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50)),
                ('is_conclusion', models.BooleanField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='argupedia.Scheme')),
            ],
        ),
    ]
