# Generated by Django 2.2.7 on 2019-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0009_schemestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemestructure',
            name='ordering',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50),
        ),
    ]
