# Generated by Django 2.2.7 on 2019-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0010_auto_20191124_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemestructure',
            name='section_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
