# Generated by Django 2.2.7 on 2019-12-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0011_schemestructure_section_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='deleted',
        ),
    ]
