# Generated by Django 2.2.7 on 2019-12-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0013_auto_20191201_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='scheme_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_used', to='argupedia.Scheme'),
        ),
    ]
