# Generated by Django 2.2.7 on 2019-12-01 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0014_entry_scheme_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='scheme_used',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_used', to='argupedia.Scheme'),
            preserve_default=False,
        ),
    ]
