# Generated by Django 2.2.7 on 2020-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0015_auto_20191201_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_in',
            field=models.BooleanField(null=True),
        ),
    ]
