# Generated by Django 2.2.7 on 2020-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0016_entry_is_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_in',
            field=models.NullBooleanField(default=None, max_length=3),
        ),
    ]
