# Generated by Django 2.2.7 on 2020-03-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argupedia', '0017_auto_20200308_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_in',
        ),
    ]
